
// File auto-generated by Padrick unknown
// 
// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
package pkg_astral_padframe;

  //Structs for botl

  //Static connections signals
   typedef struct packed {
      logic       [1:0] drive_strength_grp_1;
      logic       [1:0] drive_strength_grp_2;
      logic       [1:0] drive_strength_grp_3;
      logic       [1:0] drive_strength_grp_4;
      logic       [1:0] drive_strength_grp_5;
      logic       [1:0] drive_strength_grp_6;
      logic       [1:0] drive_strength_grp_7;
      logic       [1:0] drive_strength_grp_8;
      logic       [1:0] drive_strength_grp_9;
      logic       [1:0] drive_strength_grp_10;
      logic       [1:0] drive_strength_grp_11;
      logic        fll_host_clk_o;
      logic        fll_secd_clk_o;
      logic        gpio_v_o_0;
      logic        gpio_v_o_1;
      logic        gpio_v_o_2;
      logic        gpio_v_o_3;
      logic        gpio_v_oen_i_0;
      logic        gpio_v_oen_i_1;
      logic        gpio_v_oen_i_2;
      logic        gpio_v_oen_i_3;
      logic        jtag_ot_tdo_o;
      logic        jtag_tdo_o;
      logic        ot_uart_tx_o;
      logic        slew_en_grp_1;
      logic        slew_en_grp_2;
      logic        slew_en_grp_3;
      logic        slew_en_grp_4;
      logic        slew_en_grp_5;
      logic        slew_en_grp_6;
      logic        slew_en_grp_7;
      logic        slew_en_grp_8;
      logic        slew_en_grp_9;
      logic        slew_en_grp_10;
      logic        slew_en_grp_11;
      logic        spih_csb_o_1;
      logic        spih_ot_csb_o;
      logic        spih_ot_sck_o;
      logic        spih_ot_sd_o_1;
      logic        spih_ot_sd_o_2;
      logic        spih_ot_sd_o_3;
      logic        spih_ot_sd_o_4;
      logic        spih_ot_sd_oen_i_1;
      logic        spih_ot_sd_oen_i_2;
      logic        spih_ot_sd_oen_i_3;
      logic        spih_ot_sd_oen_i_4;
      logic        spih_sck_o;
      logic        spih_sd_o_0;
      logic        spih_sd_o_1;
      logic        spih_sd_o_2;
      logic        spih_sd_o_3;
      logic        spih_sd_oen_i_0;
      logic        spih_sd_oen_i_1;
      logic        spih_sd_oen_i_2;
      logic        spih_sd_oen_i_3;
      logic        uart_tx_o;
     } pad_domain_botl_static_connection_signals_soc2pad_t;

   typedef struct packed {
      logic        boot_mode_i_0;
      logic        boot_mode_i_1;
      logic        fll_bypass_i;
      logic        gpio_v_i_0;
      logic        gpio_v_i_1;
      logic        gpio_v_i_2;
      logic        gpio_v_i_3;
      logic        jtag_ot_tclk_i;
      logic        jtag_ot_tdi_i;
      logic        jtag_ot_tms_i;
      logic        jtag_ot_trst_ni;
      logic        jtag_tclk_i;
      logic        jtag_tdi_i;
      logic        jtag_tms_i;
      logic        jtag_trst_ni;
      logic        ot_boot_mode_i;
      logic        ot_uart_rx_i;
      logic        pwr_on_rst_ni;
      logic        ref_clk_i;
      logic        secure_boot_i;
      logic        spih_ot_sd_i_1;
      logic        spih_ot_sd_i_2;
      logic        spih_ot_sd_i_3;
      logic        spih_ot_sd_i_4;
      logic        spih_sd_i_0;
      logic        spih_sd_i_1;
      logic        spih_sd_i_2;
      logic        spih_sd_i_3;
      logic        uart_rx_i;
     } pad_domain_botl_static_connection_signals_pad2soc_t;


  //Toplevel structs

  typedef struct packed {
    pad_domain_botl_static_connection_signals_pad2soc_t botl;
  } static_connection_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_botl_static_connection_signals_soc2pad_t botl;
  } static_connection_signals_soc2pad_t;



endpackage : pkg_astral_padframe
