
// File auto-generated by Padrick unknown
// 
// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
package pkg_internal_astral_padframe_botl;


  // Indices definitions

  // Dynamic Pad  instance index
endpackage : pkg_internal_astral_padframe_botl
