
// File auto-generated by Padrick unknown
// 
// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
package pkg_astral_padframe;

  //Structs for botl

  //Static connections signals
   typedef struct packed {
      logic        fll_host_clk_o;
      logic       [1:0] fll_host_drv_str;
      logic        fll_host_slew_en;
      logic        fll_secd_clk_o;
      logic       [1:0] fll_secd_drv_str;
      logic        fll_secd_slew_en;
      logic       [1:0] gpio_0_drv_str;
      logic        gpio_0_in_en;
      logic        gpio_0_out_en;
      logic        gpio_0_pd_en;
      logic        gpio_0_pu_en;
      logic        gpio_0_slew_en;
      logic        gpio_0_smt_en;
      logic       [1:0] gpio_1_drv_str;
      logic        gpio_1_in_en;
      logic        gpio_1_out_en;
      logic        gpio_1_pd_en;
      logic        gpio_1_pu_en;
      logic        gpio_1_slew_en;
      logic        gpio_1_smt_en;
      logic       [1:0] gpio_2_drv_str;
      logic        gpio_2_in_en;
      logic        gpio_2_out_en;
      logic        gpio_2_pd_en;
      logic        gpio_2_pu_en;
      logic        gpio_2_slew_en;
      logic        gpio_2_smt_en;
      logic       [1:0] gpio_3_drv_str;
      logic        gpio_3_in_en;
      logic        gpio_3_out_en;
      logic        gpio_3_pd_en;
      logic        gpio_3_pu_en;
      logic        gpio_3_slew_en;
      logic        gpio_3_smt_en;
      logic        gpio_v_o_0;
      logic        gpio_v_o_1;
      logic        gpio_v_o_2;
      logic        gpio_v_o_3;
      logic       [1:0] jtag_ot_tdo_drv_str;
      logic        jtag_ot_tdo_o;
      logic        jtag_ot_tdo_slew_en;
      logic       [1:0] jtag_tdo_drv_str;
      logic        jtag_tdo_o;
      logic        jtag_tdo_slew_en;
      logic       [1:0] ot_uart_tx_drv_str;
      logic        ot_uart_tx_o;
      logic        ot_uart_tx_slew_en;
      logic       [1:0] spih_csb_drv_str;
      logic        spih_csb_o_1;
      logic        spih_csb_out_en;
      logic        spih_csb_slew_en;
      logic       [1:0] spih_ot_csb_drv_str;
      logic        spih_ot_csb_o;
      logic        spih_ot_csb_out_en;
      logic        spih_ot_csb_slew_en;
      logic       [1:0] spih_ot_sck_drv_str;
      logic        spih_ot_sck_o;
      logic        spih_ot_sck_out_en;
      logic        spih_ot_sck_slew_en;
      logic       [1:0] spih_ot_sd_0_drv_str;
      logic        spih_ot_sd_0_in_en;
      logic        spih_ot_sd_0_out_en;
      logic        spih_ot_sd_0_pd_en;
      logic        spih_ot_sd_0_pu_en;
      logic        spih_ot_sd_0_slew_en;
      logic        spih_ot_sd_0_smt_en;
      logic       [1:0] spih_ot_sd_1_drv_str;
      logic        spih_ot_sd_1_in_en;
      logic        spih_ot_sd_1_out_en;
      logic        spih_ot_sd_1_pd_en;
      logic        spih_ot_sd_1_pu_en;
      logic        spih_ot_sd_1_slew_en;
      logic        spih_ot_sd_1_smt_en;
      logic       [1:0] spih_ot_sd_2_drv_str;
      logic        spih_ot_sd_2_in_en;
      logic        spih_ot_sd_2_out_en;
      logic        spih_ot_sd_2_pd_en;
      logic        spih_ot_sd_2_pu_en;
      logic        spih_ot_sd_2_slew_en;
      logic        spih_ot_sd_2_smt_en;
      logic       [1:0] spih_ot_sd_3_drv_str;
      logic        spih_ot_sd_3_in_en;
      logic        spih_ot_sd_3_out_en;
      logic        spih_ot_sd_3_pd_en;
      logic        spih_ot_sd_3_pu_en;
      logic        spih_ot_sd_3_slew_en;
      logic        spih_ot_sd_3_smt_en;
      logic        spih_ot_sd_o_0;
      logic        spih_ot_sd_o_1;
      logic        spih_ot_sd_o_2;
      logic        spih_ot_sd_o_3;
      logic       [1:0] spih_sck_drv_str;
      logic        spih_sck_o;
      logic        spih_sck_out_en;
      logic        spih_sck_slew_en;
      logic       [1:0] spih_sd_0_drv_str;
      logic        spih_sd_0_in_en;
      logic        spih_sd_0_out_en;
      logic        spih_sd_0_pd_en;
      logic        spih_sd_0_pu_en;
      logic        spih_sd_0_slew_en;
      logic        spih_sd_0_smt_en;
      logic       [1:0] spih_sd_1_drv_str;
      logic        spih_sd_1_in_en;
      logic        spih_sd_1_out_en;
      logic        spih_sd_1_pd_en;
      logic        spih_sd_1_pu_en;
      logic        spih_sd_1_slew_en;
      logic        spih_sd_1_smt_en;
      logic       [1:0] spih_sd_2_drv_str;
      logic        spih_sd_2_in_en;
      logic        spih_sd_2_out_en;
      logic        spih_sd_2_pd_en;
      logic        spih_sd_2_pu_en;
      logic        spih_sd_2_slew_en;
      logic        spih_sd_2_smt_en;
      logic       [1:0] spih_sd_3_drv_str;
      logic        spih_sd_3_in_en;
      logic        spih_sd_3_out_en;
      logic        spih_sd_3_pd_en;
      logic        spih_sd_3_pu_en;
      logic        spih_sd_3_slew_en;
      logic        spih_sd_3_smt_en;
      logic        spih_sd_o_0;
      logic        spih_sd_o_1;
      logic        spih_sd_o_2;
      logic        spih_sd_o_3;
      logic       [1:0] uart_tx_drv_str;
      logic        uart_tx_o;
      logic        uart_tx_slew_en;
     } pad_domain_botl_static_connection_signals_soc2pad_t;

   typedef struct packed {
      logic        boot_mode_i_0;
      logic        boot_mode_i_1;
      logic        fll_bypass_i;
      logic        gpio_v_i_0;
      logic        gpio_v_i_1;
      logic        gpio_v_i_2;
      logic        gpio_v_i_3;
      logic        jtag_ot_tclk_i;
      logic        jtag_ot_tdi_i;
      logic        jtag_ot_tms_i;
      logic        jtag_ot_trst_ni;
      logic        jtag_tclk_i;
      logic        jtag_tdi_i;
      logic        jtag_tms_i;
      logic        jtag_trst_ni;
      logic        ot_boot_mode_i;
      logic        ot_uart_rx_i;
      logic        pwr_on_rst_ni;
      logic        ref_clk_i;
      logic        secure_boot_i;
      logic        spih_ot_sd_i_0;
      logic        spih_ot_sd_i_1;
      logic        spih_ot_sd_i_2;
      logic        spih_ot_sd_i_3;
      logic        spih_sd_i_0;
      logic        spih_sd_i_1;
      logic        spih_sd_i_2;
      logic        spih_sd_i_3;
      logic        uart_rx_i;
     } pad_domain_botl_static_connection_signals_pad2soc_t;


  //Toplevel structs

  typedef struct packed {
    pad_domain_botl_static_connection_signals_pad2soc_t botl;
  } static_connection_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_botl_static_connection_signals_soc2pad_t botl;
  } static_connection_signals_soc2pad_t;



endpackage : pkg_astral_padframe
