// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package top_padframe_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padgroup_count;
  } top_padframe_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_1;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_2;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_3;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_4;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_5;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_6;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_7;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_8;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_9;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_10;
    struct packed {
      logic [1:0]  q;
    } drv_str_pg_11;
  } top_padframe_config_reg2hw_drv_str_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } slw_pg_1;
    struct packed {
      logic        q;
    } slw_pg_2;
    struct packed {
      logic        q;
    } slw_pg_3;
    struct packed {
      logic        q;
    } slw_pg_4;
    struct packed {
      logic        q;
    } slw_pg_5;
    struct packed {
      logic        q;
    } slw_pg_6;
    struct packed {
      logic        q;
    } slw_pg_7;
    struct packed {
      logic        q;
    } slw_pg_8;
    struct packed {
      logic        q;
    } slw_pg_9;
    struct packed {
      logic        q;
    } slw_pg_10;
    struct packed {
      logic        q;
    } slw_pg_11;
  } top_padframe_config_reg2hw_slw_cfg_reg_t;

  // Register -> HW type
  typedef struct packed {
    top_padframe_config_reg2hw_info_reg_t info; // [64:33]
    top_padframe_config_reg2hw_drv_str_cfg_reg_t drv_str_cfg; // [32:11]
    top_padframe_config_reg2hw_slw_cfg_reg_t slw_cfg; // [10:0]
  } top_padframe_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] TOP_PADFRAME_CONFIG_INFO_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] TOP_PADFRAME_CONFIG_DRV_STR_CFG_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] TOP_PADFRAME_CONFIG_SLW_CFG_OFFSET = 4'h 8;

  // Register index
  typedef enum int {
    TOP_PADFRAME_CONFIG_INFO,
    TOP_PADFRAME_CONFIG_DRV_STR_CFG,
    TOP_PADFRAME_CONFIG_SLW_CFG
  } top_padframe_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] TOP_PADFRAME_CONFIG_PERMIT [3] = '{
    4'b 1111, // index[0] TOP_PADFRAME_CONFIG_INFO
    4'b 0111, // index[1] TOP_PADFRAME_CONFIG_DRV_STR_CFG
    4'b 0011  // index[2] TOP_PADFRAME_CONFIG_SLW_CFG
  };

endpackage

