// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module top_padframe_config_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 7
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output top_padframe_config_reg_pkg::top_padframe_config_reg2hw_t reg2hw, // Write


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import top_padframe_config_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [15:0] info_hw_version_qs;
  logic [15:0] info_pad_count_qs;
  logic pad_fll_host_slew_en_qs;
  logic pad_fll_host_slew_en_wd;
  logic pad_fll_host_slew_en_we;
  logic [1:0] pad_fll_host_drv_str_qs;
  logic [1:0] pad_fll_host_drv_str_wd;
  logic pad_fll_host_drv_str_we;
  logic pad_fll_secd_slew_en_qs;
  logic pad_fll_secd_slew_en_wd;
  logic pad_fll_secd_slew_en_we;
  logic [1:0] pad_fll_secd_drv_str_qs;
  logic [1:0] pad_fll_secd_drv_str_wd;
  logic pad_fll_secd_drv_str_we;
  logic pad_jtag_tdo_slew_en_qs;
  logic pad_jtag_tdo_slew_en_wd;
  logic pad_jtag_tdo_slew_en_we;
  logic [1:0] pad_jtag_tdo_drv_str_qs;
  logic [1:0] pad_jtag_tdo_drv_str_wd;
  logic pad_jtag_tdo_drv_str_we;
  logic pad_uart_tx_slew_en_qs;
  logic pad_uart_tx_slew_en_wd;
  logic pad_uart_tx_slew_en_we;
  logic [1:0] pad_uart_tx_drv_str_qs;
  logic [1:0] pad_uart_tx_drv_str_wd;
  logic pad_uart_tx_drv_str_we;
  logic pad_gpio_0_pad_en_qs;
  logic pad_gpio_0_pad_en_wd;
  logic pad_gpio_0_pad_en_we;
  logic pad_gpio_0_slew_en_qs;
  logic pad_gpio_0_slew_en_wd;
  logic pad_gpio_0_slew_en_we;
  logic [1:0] pad_gpio_0_drv_str_qs;
  logic [1:0] pad_gpio_0_drv_str_wd;
  logic pad_gpio_0_drv_str_we;
  logic pad_gpio_0_pd_en_qs;
  logic pad_gpio_0_pd_en_wd;
  logic pad_gpio_0_pd_en_we;
  logic pad_gpio_0_pu_en_qs;
  logic pad_gpio_0_pu_en_wd;
  logic pad_gpio_0_pu_en_we;
  logic pad_gpio_0_smt_en_qs;
  logic pad_gpio_0_smt_en_wd;
  logic pad_gpio_0_smt_en_we;
  logic pad_gpio_1_pad_en_qs;
  logic pad_gpio_1_pad_en_wd;
  logic pad_gpio_1_pad_en_we;
  logic pad_gpio_1_slew_en_qs;
  logic pad_gpio_1_slew_en_wd;
  logic pad_gpio_1_slew_en_we;
  logic [1:0] pad_gpio_1_drv_str_qs;
  logic [1:0] pad_gpio_1_drv_str_wd;
  logic pad_gpio_1_drv_str_we;
  logic pad_gpio_1_pd_en_qs;
  logic pad_gpio_1_pd_en_wd;
  logic pad_gpio_1_pd_en_we;
  logic pad_gpio_1_pu_en_qs;
  logic pad_gpio_1_pu_en_wd;
  logic pad_gpio_1_pu_en_we;
  logic pad_gpio_1_smt_en_qs;
  logic pad_gpio_1_smt_en_wd;
  logic pad_gpio_1_smt_en_we;
  logic pad_gpio_2_pad_en_qs;
  logic pad_gpio_2_pad_en_wd;
  logic pad_gpio_2_pad_en_we;
  logic pad_gpio_2_slew_en_qs;
  logic pad_gpio_2_slew_en_wd;
  logic pad_gpio_2_slew_en_we;
  logic [1:0] pad_gpio_2_drv_str_qs;
  logic [1:0] pad_gpio_2_drv_str_wd;
  logic pad_gpio_2_drv_str_we;
  logic pad_gpio_2_pd_en_qs;
  logic pad_gpio_2_pd_en_wd;
  logic pad_gpio_2_pd_en_we;
  logic pad_gpio_2_pu_en_qs;
  logic pad_gpio_2_pu_en_wd;
  logic pad_gpio_2_pu_en_we;
  logic pad_gpio_2_smt_en_qs;
  logic pad_gpio_2_smt_en_wd;
  logic pad_gpio_2_smt_en_we;
  logic pad_gpio_3_pad_en_qs;
  logic pad_gpio_3_pad_en_wd;
  logic pad_gpio_3_pad_en_we;
  logic pad_gpio_3_slew_en_qs;
  logic pad_gpio_3_slew_en_wd;
  logic pad_gpio_3_slew_en_we;
  logic [1:0] pad_gpio_3_drv_str_qs;
  logic [1:0] pad_gpio_3_drv_str_wd;
  logic pad_gpio_3_drv_str_we;
  logic pad_gpio_3_pd_en_qs;
  logic pad_gpio_3_pd_en_wd;
  logic pad_gpio_3_pd_en_we;
  logic pad_gpio_3_pu_en_qs;
  logic pad_gpio_3_pu_en_wd;
  logic pad_gpio_3_pu_en_we;
  logic pad_gpio_3_smt_en_qs;
  logic pad_gpio_3_smt_en_wd;
  logic pad_gpio_3_smt_en_we;
  logic pad_jtag_ot_tdo_slew_en_qs;
  logic pad_jtag_ot_tdo_slew_en_wd;
  logic pad_jtag_ot_tdo_slew_en_we;
  logic [1:0] pad_jtag_ot_tdo_drv_str_qs;
  logic [1:0] pad_jtag_ot_tdo_drv_str_wd;
  logic pad_jtag_ot_tdo_drv_str_we;
  logic pad_ot_uart_tx_slew_en_qs;
  logic pad_ot_uart_tx_slew_en_wd;
  logic pad_ot_uart_tx_slew_en_we;
  logic [1:0] pad_ot_uart_tx_drv_str_qs;
  logic [1:0] pad_ot_uart_tx_drv_str_wd;
  logic pad_ot_uart_tx_drv_str_we;
  logic pad_spih_sck_pad_en_qs;
  logic pad_spih_sck_pad_en_wd;
  logic pad_spih_sck_pad_en_we;
  logic pad_spih_sck_slew_en_qs;
  logic pad_spih_sck_slew_en_wd;
  logic pad_spih_sck_slew_en_we;
  logic [1:0] pad_spih_sck_drv_str_qs;
  logic [1:0] pad_spih_sck_drv_str_wd;
  logic pad_spih_sck_drv_str_we;
  logic pad_spih_csb_pad_en_qs;
  logic pad_spih_csb_pad_en_wd;
  logic pad_spih_csb_pad_en_we;
  logic pad_spih_csb_slew_en_qs;
  logic pad_spih_csb_slew_en_wd;
  logic pad_spih_csb_slew_en_we;
  logic [1:0] pad_spih_csb_drv_str_qs;
  logic [1:0] pad_spih_csb_drv_str_wd;
  logic pad_spih_csb_drv_str_we;
  logic pad_spih_sd_0_pad_en_qs;
  logic pad_spih_sd_0_pad_en_wd;
  logic pad_spih_sd_0_pad_en_we;
  logic pad_spih_sd_0_slew_en_qs;
  logic pad_spih_sd_0_slew_en_wd;
  logic pad_spih_sd_0_slew_en_we;
  logic [1:0] pad_spih_sd_0_drv_str_qs;
  logic [1:0] pad_spih_sd_0_drv_str_wd;
  logic pad_spih_sd_0_drv_str_we;
  logic pad_spih_sd_0_pd_en_qs;
  logic pad_spih_sd_0_pd_en_wd;
  logic pad_spih_sd_0_pd_en_we;
  logic pad_spih_sd_0_pu_en_qs;
  logic pad_spih_sd_0_pu_en_wd;
  logic pad_spih_sd_0_pu_en_we;
  logic pad_spih_sd_0_smt_en_qs;
  logic pad_spih_sd_0_smt_en_wd;
  logic pad_spih_sd_0_smt_en_we;
  logic pad_spih_sd_1_pad_en_qs;
  logic pad_spih_sd_1_pad_en_wd;
  logic pad_spih_sd_1_pad_en_we;
  logic pad_spih_sd_1_slew_en_qs;
  logic pad_spih_sd_1_slew_en_wd;
  logic pad_spih_sd_1_slew_en_we;
  logic [1:0] pad_spih_sd_1_drv_str_qs;
  logic [1:0] pad_spih_sd_1_drv_str_wd;
  logic pad_spih_sd_1_drv_str_we;
  logic pad_spih_sd_1_pd_en_qs;
  logic pad_spih_sd_1_pd_en_wd;
  logic pad_spih_sd_1_pd_en_we;
  logic pad_spih_sd_1_pu_en_qs;
  logic pad_spih_sd_1_pu_en_wd;
  logic pad_spih_sd_1_pu_en_we;
  logic pad_spih_sd_1_smt_en_qs;
  logic pad_spih_sd_1_smt_en_wd;
  logic pad_spih_sd_1_smt_en_we;
  logic pad_spih_sd_2_pad_en_qs;
  logic pad_spih_sd_2_pad_en_wd;
  logic pad_spih_sd_2_pad_en_we;
  logic pad_spih_sd_2_slew_en_qs;
  logic pad_spih_sd_2_slew_en_wd;
  logic pad_spih_sd_2_slew_en_we;
  logic [1:0] pad_spih_sd_2_drv_str_qs;
  logic [1:0] pad_spih_sd_2_drv_str_wd;
  logic pad_spih_sd_2_drv_str_we;
  logic pad_spih_sd_2_pd_en_qs;
  logic pad_spih_sd_2_pd_en_wd;
  logic pad_spih_sd_2_pd_en_we;
  logic pad_spih_sd_2_pu_en_qs;
  logic pad_spih_sd_2_pu_en_wd;
  logic pad_spih_sd_2_pu_en_we;
  logic pad_spih_sd_2_smt_en_qs;
  logic pad_spih_sd_2_smt_en_wd;
  logic pad_spih_sd_2_smt_en_we;
  logic pad_spih_sd_3_pad_en_qs;
  logic pad_spih_sd_3_pad_en_wd;
  logic pad_spih_sd_3_pad_en_we;
  logic pad_spih_sd_3_slew_en_qs;
  logic pad_spih_sd_3_slew_en_wd;
  logic pad_spih_sd_3_slew_en_we;
  logic [1:0] pad_spih_sd_3_drv_str_qs;
  logic [1:0] pad_spih_sd_3_drv_str_wd;
  logic pad_spih_sd_3_drv_str_we;
  logic pad_spih_sd_3_pd_en_qs;
  logic pad_spih_sd_3_pd_en_wd;
  logic pad_spih_sd_3_pd_en_we;
  logic pad_spih_sd_3_pu_en_qs;
  logic pad_spih_sd_3_pu_en_wd;
  logic pad_spih_sd_3_pu_en_we;
  logic pad_spih_sd_3_smt_en_qs;
  logic pad_spih_sd_3_smt_en_wd;
  logic pad_spih_sd_3_smt_en_we;
  logic pad_spih_ot_sck_pad_en_qs;
  logic pad_spih_ot_sck_pad_en_wd;
  logic pad_spih_ot_sck_pad_en_we;
  logic pad_spih_ot_sck_slew_en_qs;
  logic pad_spih_ot_sck_slew_en_wd;
  logic pad_spih_ot_sck_slew_en_we;
  logic [1:0] pad_spih_ot_sck_drv_str_qs;
  logic [1:0] pad_spih_ot_sck_drv_str_wd;
  logic pad_spih_ot_sck_drv_str_we;
  logic pad_spih_ot_csb_pad_en_qs;
  logic pad_spih_ot_csb_pad_en_wd;
  logic pad_spih_ot_csb_pad_en_we;
  logic pad_spih_ot_csb_slew_en_qs;
  logic pad_spih_ot_csb_slew_en_wd;
  logic pad_spih_ot_csb_slew_en_we;
  logic [1:0] pad_spih_ot_csb_drv_str_qs;
  logic [1:0] pad_spih_ot_csb_drv_str_wd;
  logic pad_spih_ot_csb_drv_str_we;
  logic pad_spih_ot_sd_0_pad_en_qs;
  logic pad_spih_ot_sd_0_pad_en_wd;
  logic pad_spih_ot_sd_0_pad_en_we;
  logic pad_spih_ot_sd_0_slew_en_qs;
  logic pad_spih_ot_sd_0_slew_en_wd;
  logic pad_spih_ot_sd_0_slew_en_we;
  logic [1:0] pad_spih_ot_sd_0_drv_str_qs;
  logic [1:0] pad_spih_ot_sd_0_drv_str_wd;
  logic pad_spih_ot_sd_0_drv_str_we;
  logic pad_spih_ot_sd_0_pd_en_qs;
  logic pad_spih_ot_sd_0_pd_en_wd;
  logic pad_spih_ot_sd_0_pd_en_we;
  logic pad_spih_ot_sd_0_pu_en_qs;
  logic pad_spih_ot_sd_0_pu_en_wd;
  logic pad_spih_ot_sd_0_pu_en_we;
  logic pad_spih_ot_sd_0_smt_en_qs;
  logic pad_spih_ot_sd_0_smt_en_wd;
  logic pad_spih_ot_sd_0_smt_en_we;
  logic pad_spih_ot_sd_1_pad_en_qs;
  logic pad_spih_ot_sd_1_pad_en_wd;
  logic pad_spih_ot_sd_1_pad_en_we;
  logic pad_spih_ot_sd_1_slew_en_qs;
  logic pad_spih_ot_sd_1_slew_en_wd;
  logic pad_spih_ot_sd_1_slew_en_we;
  logic [1:0] pad_spih_ot_sd_1_drv_str_qs;
  logic [1:0] pad_spih_ot_sd_1_drv_str_wd;
  logic pad_spih_ot_sd_1_drv_str_we;
  logic pad_spih_ot_sd_1_pd_en_qs;
  logic pad_spih_ot_sd_1_pd_en_wd;
  logic pad_spih_ot_sd_1_pd_en_we;
  logic pad_spih_ot_sd_1_pu_en_qs;
  logic pad_spih_ot_sd_1_pu_en_wd;
  logic pad_spih_ot_sd_1_pu_en_we;
  logic pad_spih_ot_sd_1_smt_en_qs;
  logic pad_spih_ot_sd_1_smt_en_wd;
  logic pad_spih_ot_sd_1_smt_en_we;
  logic pad_spih_ot_sd_2_pad_en_qs;
  logic pad_spih_ot_sd_2_pad_en_wd;
  logic pad_spih_ot_sd_2_pad_en_we;
  logic pad_spih_ot_sd_2_slew_en_qs;
  logic pad_spih_ot_sd_2_slew_en_wd;
  logic pad_spih_ot_sd_2_slew_en_we;
  logic [1:0] pad_spih_ot_sd_2_drv_str_qs;
  logic [1:0] pad_spih_ot_sd_2_drv_str_wd;
  logic pad_spih_ot_sd_2_drv_str_we;
  logic pad_spih_ot_sd_2_pd_en_qs;
  logic pad_spih_ot_sd_2_pd_en_wd;
  logic pad_spih_ot_sd_2_pd_en_we;
  logic pad_spih_ot_sd_2_pu_en_qs;
  logic pad_spih_ot_sd_2_pu_en_wd;
  logic pad_spih_ot_sd_2_pu_en_we;
  logic pad_spih_ot_sd_2_smt_en_qs;
  logic pad_spih_ot_sd_2_smt_en_wd;
  logic pad_spih_ot_sd_2_smt_en_we;
  logic pad_spih_ot_sd_3_pad_en_qs;
  logic pad_spih_ot_sd_3_pad_en_wd;
  logic pad_spih_ot_sd_3_pad_en_we;
  logic pad_spih_ot_sd_3_slew_en_qs;
  logic pad_spih_ot_sd_3_slew_en_wd;
  logic pad_spih_ot_sd_3_slew_en_we;
  logic [1:0] pad_spih_ot_sd_3_drv_str_qs;
  logic [1:0] pad_spih_ot_sd_3_drv_str_wd;
  logic pad_spih_ot_sd_3_drv_str_we;
  logic pad_spih_ot_sd_3_pd_en_qs;
  logic pad_spih_ot_sd_3_pd_en_wd;
  logic pad_spih_ot_sd_3_pd_en_we;
  logic pad_spih_ot_sd_3_pu_en_qs;
  logic pad_spih_ot_sd_3_pu_en_wd;
  logic pad_spih_ot_sd_3_pu_en_we;
  logic pad_spih_ot_sd_3_smt_en_qs;
  logic pad_spih_ot_sd_3_smt_en_wd;
  logic pad_spih_ot_sd_3_smt_en_we;

  // Register instances
  // R[info]: V(False)

  //   F[hw_version]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h2)
  ) u_info_hw_version (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.info.hw_version.q ),

    // to register interface (read)
    .qs     (info_hw_version_qs)
  );


  //   F[pad_count]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h16)
  ) u_info_pad_count (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.info.pad_count.q ),

    // to register interface (read)
    .qs     (info_pad_count_qs)
  );


  // R[pad_fll_host]: V(False)

  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_fll_host_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_fll_host_slew_en_we),
    .wd     (pad_fll_host_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_fll_host.slew_en.q ),

    // to register interface (read)
    .qs     (pad_fll_host_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_fll_host_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_fll_host_drv_str_we),
    .wd     (pad_fll_host_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_fll_host.drv_str.q ),

    // to register interface (read)
    .qs     (pad_fll_host_drv_str_qs)
  );


  // R[pad_fll_secd]: V(False)

  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_fll_secd_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_fll_secd_slew_en_we),
    .wd     (pad_fll_secd_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_fll_secd.slew_en.q ),

    // to register interface (read)
    .qs     (pad_fll_secd_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_fll_secd_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_fll_secd_drv_str_we),
    .wd     (pad_fll_secd_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_fll_secd.drv_str.q ),

    // to register interface (read)
    .qs     (pad_fll_secd_drv_str_qs)
  );


  // R[pad_jtag_tdo]: V(False)

  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_jtag_tdo_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_jtag_tdo_slew_en_we),
    .wd     (pad_jtag_tdo_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_jtag_tdo.slew_en.q ),

    // to register interface (read)
    .qs     (pad_jtag_tdo_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_jtag_tdo_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_jtag_tdo_drv_str_we),
    .wd     (pad_jtag_tdo_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_jtag_tdo.drv_str.q ),

    // to register interface (read)
    .qs     (pad_jtag_tdo_drv_str_qs)
  );


  // R[pad_uart_tx]: V(False)

  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_uart_tx_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_uart_tx_slew_en_we),
    .wd     (pad_uart_tx_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_uart_tx.slew_en.q ),

    // to register interface (read)
    .qs     (pad_uart_tx_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_uart_tx_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_uart_tx_drv_str_we),
    .wd     (pad_uart_tx_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_uart_tx.drv_str.q ),

    // to register interface (read)
    .qs     (pad_uart_tx_drv_str_qs)
  );


  // R[pad_gpio_0]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_0_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_0_pad_en_we),
    .wd     (pad_gpio_0_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_0.pad_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_0_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_0_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_0_slew_en_we),
    .wd     (pad_gpio_0_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_0.slew_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_0_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_gpio_0_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_0_drv_str_we),
    .wd     (pad_gpio_0_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_0.drv_str.q ),

    // to register interface (read)
    .qs     (pad_gpio_0_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_0_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_0_pd_en_we),
    .wd     (pad_gpio_0_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_0.pd_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_0_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_0_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_0_pu_en_we),
    .wd     (pad_gpio_0_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_0.pu_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_0_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_0_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_0_smt_en_we),
    .wd     (pad_gpio_0_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_0.smt_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_0_smt_en_qs)
  );


  // R[pad_gpio_1]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_1_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_1_pad_en_we),
    .wd     (pad_gpio_1_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_1.pad_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_1_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_1_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_1_slew_en_we),
    .wd     (pad_gpio_1_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_1.slew_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_1_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_gpio_1_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_1_drv_str_we),
    .wd     (pad_gpio_1_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_1.drv_str.q ),

    // to register interface (read)
    .qs     (pad_gpio_1_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_1_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_1_pd_en_we),
    .wd     (pad_gpio_1_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_1.pd_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_1_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_1_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_1_pu_en_we),
    .wd     (pad_gpio_1_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_1.pu_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_1_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_1_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_1_smt_en_we),
    .wd     (pad_gpio_1_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_1.smt_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_1_smt_en_qs)
  );


  // R[pad_gpio_2]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_2_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_2_pad_en_we),
    .wd     (pad_gpio_2_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_2.pad_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_2_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_2_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_2_slew_en_we),
    .wd     (pad_gpio_2_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_2.slew_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_2_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_gpio_2_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_2_drv_str_we),
    .wd     (pad_gpio_2_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_2.drv_str.q ),

    // to register interface (read)
    .qs     (pad_gpio_2_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_2_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_2_pd_en_we),
    .wd     (pad_gpio_2_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_2.pd_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_2_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_2_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_2_pu_en_we),
    .wd     (pad_gpio_2_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_2.pu_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_2_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_2_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_2_smt_en_we),
    .wd     (pad_gpio_2_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_2.smt_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_2_smt_en_qs)
  );


  // R[pad_gpio_3]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_3_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_3_pad_en_we),
    .wd     (pad_gpio_3_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_3.pad_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_3_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_3_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_3_slew_en_we),
    .wd     (pad_gpio_3_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_3.slew_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_3_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_gpio_3_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_3_drv_str_we),
    .wd     (pad_gpio_3_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_3.drv_str.q ),

    // to register interface (read)
    .qs     (pad_gpio_3_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_3_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_3_pd_en_we),
    .wd     (pad_gpio_3_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_3.pd_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_3_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_3_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_3_pu_en_we),
    .wd     (pad_gpio_3_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_3.pu_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_3_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_gpio_3_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_gpio_3_smt_en_we),
    .wd     (pad_gpio_3_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_gpio_3.smt_en.q ),

    // to register interface (read)
    .qs     (pad_gpio_3_smt_en_qs)
  );


  // R[pad_jtag_ot_tdo]: V(False)

  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_jtag_ot_tdo_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_jtag_ot_tdo_slew_en_we),
    .wd     (pad_jtag_ot_tdo_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_jtag_ot_tdo.slew_en.q ),

    // to register interface (read)
    .qs     (pad_jtag_ot_tdo_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_jtag_ot_tdo_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_jtag_ot_tdo_drv_str_we),
    .wd     (pad_jtag_ot_tdo_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_jtag_ot_tdo.drv_str.q ),

    // to register interface (read)
    .qs     (pad_jtag_ot_tdo_drv_str_qs)
  );


  // R[pad_ot_uart_tx]: V(False)

  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_ot_uart_tx_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_ot_uart_tx_slew_en_we),
    .wd     (pad_ot_uart_tx_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_ot_uart_tx.slew_en.q ),

    // to register interface (read)
    .qs     (pad_ot_uart_tx_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_ot_uart_tx_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_ot_uart_tx_drv_str_we),
    .wd     (pad_ot_uart_tx_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_ot_uart_tx.drv_str.q ),

    // to register interface (read)
    .qs     (pad_ot_uart_tx_drv_str_qs)
  );


  // R[pad_spih_sck]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sck_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sck_pad_en_we),
    .wd     (pad_spih_sck_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sck.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sck_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sck_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sck_slew_en_we),
    .wd     (pad_spih_sck_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sck.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sck_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_sck_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sck_drv_str_we),
    .wd     (pad_spih_sck_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sck.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_sck_drv_str_qs)
  );


  // R[pad_spih_csb]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_csb_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_csb_pad_en_we),
    .wd     (pad_spih_csb_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_csb.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_csb_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_csb_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_csb_slew_en_we),
    .wd     (pad_spih_csb_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_csb.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_csb_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_csb_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_csb_drv_str_we),
    .wd     (pad_spih_csb_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_csb.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_csb_drv_str_qs)
  );


  // R[pad_spih_sd_0]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_0_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_0_pad_en_we),
    .wd     (pad_spih_sd_0_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_0.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_0_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_0_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_0_slew_en_we),
    .wd     (pad_spih_sd_0_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_0.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_0_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_sd_0_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_0_drv_str_we),
    .wd     (pad_spih_sd_0_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_0.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_0_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_0_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_0_pd_en_we),
    .wd     (pad_spih_sd_0_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_0.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_0_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_0_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_0_pu_en_we),
    .wd     (pad_spih_sd_0_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_0.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_0_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_0_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_0_smt_en_we),
    .wd     (pad_spih_sd_0_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_0.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_0_smt_en_qs)
  );


  // R[pad_spih_sd_1]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_1_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_1_pad_en_we),
    .wd     (pad_spih_sd_1_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_1.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_1_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_1_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_1_slew_en_we),
    .wd     (pad_spih_sd_1_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_1.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_1_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_sd_1_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_1_drv_str_we),
    .wd     (pad_spih_sd_1_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_1.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_1_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_1_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_1_pd_en_we),
    .wd     (pad_spih_sd_1_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_1.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_1_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_1_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_1_pu_en_we),
    .wd     (pad_spih_sd_1_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_1.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_1_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_1_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_1_smt_en_we),
    .wd     (pad_spih_sd_1_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_1.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_1_smt_en_qs)
  );


  // R[pad_spih_sd_2]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_2_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_2_pad_en_we),
    .wd     (pad_spih_sd_2_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_2.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_2_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_2_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_2_slew_en_we),
    .wd     (pad_spih_sd_2_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_2.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_2_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_sd_2_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_2_drv_str_we),
    .wd     (pad_spih_sd_2_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_2.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_2_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_2_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_2_pd_en_we),
    .wd     (pad_spih_sd_2_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_2.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_2_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_2_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_2_pu_en_we),
    .wd     (pad_spih_sd_2_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_2.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_2_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_2_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_2_smt_en_we),
    .wd     (pad_spih_sd_2_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_2.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_2_smt_en_qs)
  );


  // R[pad_spih_sd_3]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_3_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_3_pad_en_we),
    .wd     (pad_spih_sd_3_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_3.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_3_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_3_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_3_slew_en_we),
    .wd     (pad_spih_sd_3_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_3.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_3_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_sd_3_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_3_drv_str_we),
    .wd     (pad_spih_sd_3_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_3.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_3_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_sd_3_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_3_pd_en_we),
    .wd     (pad_spih_sd_3_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_3.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_3_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_3_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_3_pu_en_we),
    .wd     (pad_spih_sd_3_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_3.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_3_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_sd_3_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_sd_3_smt_en_we),
    .wd     (pad_spih_sd_3_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_sd_3.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_sd_3_smt_en_qs)
  );


  // R[pad_spih_ot_sck]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sck_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sck_pad_en_we),
    .wd     (pad_spih_ot_sck_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sck.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sck_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sck_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sck_slew_en_we),
    .wd     (pad_spih_ot_sck_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sck.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sck_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_ot_sck_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sck_drv_str_we),
    .wd     (pad_spih_ot_sck_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sck.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sck_drv_str_qs)
  );


  // R[pad_spih_ot_csb]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_csb_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_csb_pad_en_we),
    .wd     (pad_spih_ot_csb_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_csb.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_csb_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_csb_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_csb_slew_en_we),
    .wd     (pad_spih_ot_csb_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_csb.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_csb_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_ot_csb_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_csb_drv_str_we),
    .wd     (pad_spih_ot_csb_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_csb.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_csb_drv_str_qs)
  );


  // R[pad_spih_ot_sd_0]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_0_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_0_pad_en_we),
    .wd     (pad_spih_ot_sd_0_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_0.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_0_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_0_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_0_slew_en_we),
    .wd     (pad_spih_ot_sd_0_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_0.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_0_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_ot_sd_0_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_0_drv_str_we),
    .wd     (pad_spih_ot_sd_0_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_0.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_0_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_0_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_0_pd_en_we),
    .wd     (pad_spih_ot_sd_0_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_0.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_0_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_0_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_0_pu_en_we),
    .wd     (pad_spih_ot_sd_0_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_0.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_0_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_0_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_0_smt_en_we),
    .wd     (pad_spih_ot_sd_0_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_0.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_0_smt_en_qs)
  );


  // R[pad_spih_ot_sd_1]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_1_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_1_pad_en_we),
    .wd     (pad_spih_ot_sd_1_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_1.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_1_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_1_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_1_slew_en_we),
    .wd     (pad_spih_ot_sd_1_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_1.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_1_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_ot_sd_1_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_1_drv_str_we),
    .wd     (pad_spih_ot_sd_1_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_1.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_1_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_1_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_1_pd_en_we),
    .wd     (pad_spih_ot_sd_1_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_1.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_1_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_1_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_1_pu_en_we),
    .wd     (pad_spih_ot_sd_1_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_1.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_1_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_1_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_1_smt_en_we),
    .wd     (pad_spih_ot_sd_1_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_1.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_1_smt_en_qs)
  );


  // R[pad_spih_ot_sd_2]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_2_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_2_pad_en_we),
    .wd     (pad_spih_ot_sd_2_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_2.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_2_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_2_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_2_slew_en_we),
    .wd     (pad_spih_ot_sd_2_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_2.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_2_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_ot_sd_2_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_2_drv_str_we),
    .wd     (pad_spih_ot_sd_2_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_2.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_2_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_2_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_2_pd_en_we),
    .wd     (pad_spih_ot_sd_2_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_2.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_2_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_2_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_2_pu_en_we),
    .wd     (pad_spih_ot_sd_2_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_2.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_2_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_2_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_2_smt_en_we),
    .wd     (pad_spih_ot_sd_2_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_2.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_2_smt_en_qs)
  );


  // R[pad_spih_ot_sd_3]: V(False)

  //   F[pad_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_3_pad_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_3_pad_en_we),
    .wd     (pad_spih_ot_sd_3_pad_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_3.pad_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_3_pad_en_qs)
  );


  //   F[slew_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_3_slew_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_3_slew_en_we),
    .wd     (pad_spih_ot_sd_3_slew_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_3.slew_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_3_slew_en_qs)
  );


  //   F[drv_str]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_pad_spih_ot_sd_3_drv_str (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_3_drv_str_we),
    .wd     (pad_spih_ot_sd_3_drv_str_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_3.drv_str.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_3_drv_str_qs)
  );


  //   F[pd_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pad_spih_ot_sd_3_pd_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_3_pd_en_we),
    .wd     (pad_spih_ot_sd_3_pd_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_3.pd_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_3_pd_en_qs)
  );


  //   F[pu_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_3_pu_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_3_pu_en_we),
    .wd     (pad_spih_ot_sd_3_pu_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_3.pu_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_3_pu_en_qs)
  );


  //   F[smt_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_pad_spih_ot_sd_3_smt_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pad_spih_ot_sd_3_smt_en_we),
    .wd     (pad_spih_ot_sd_3_smt_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pad_spih_ot_sd_3.smt_en.q ),

    // to register interface (read)
    .qs     (pad_spih_ot_sd_3_smt_en_qs)
  );




  logic [22:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == TOP_PADFRAME_CONFIG_INFO_OFFSET);
    addr_hit[ 1] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_FLL_HOST_OFFSET);
    addr_hit[ 2] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_FLL_SECD_OFFSET);
    addr_hit[ 3] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_OFFSET);
    addr_hit[ 4] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_UART_TX_OFFSET);
    addr_hit[ 5] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_GPIO_0_OFFSET);
    addr_hit[ 6] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_GPIO_1_OFFSET);
    addr_hit[ 7] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_GPIO_2_OFFSET);
    addr_hit[ 8] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_GPIO_3_OFFSET);
    addr_hit[ 9] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_OFFSET);
    addr_hit[10] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_OFFSET);
    addr_hit[11] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_OFFSET);
    addr_hit[12] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_OFFSET);
    addr_hit[13] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_OFFSET);
    addr_hit[14] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_OFFSET);
    addr_hit[15] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_OFFSET);
    addr_hit[16] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_OFFSET);
    addr_hit[17] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_OFFSET);
    addr_hit[18] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_OFFSET);
    addr_hit[19] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_OFFSET);
    addr_hit[20] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_OFFSET);
    addr_hit[21] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_OFFSET);
    addr_hit[22] = (reg_addr == TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(TOP_PADFRAME_CONFIG_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(TOP_PADFRAME_CONFIG_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(TOP_PADFRAME_CONFIG_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(TOP_PADFRAME_CONFIG_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(TOP_PADFRAME_CONFIG_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(TOP_PADFRAME_CONFIG_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(TOP_PADFRAME_CONFIG_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(TOP_PADFRAME_CONFIG_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(TOP_PADFRAME_CONFIG_PERMIT[17] & ~reg_be))) |
               (addr_hit[18] & (|(TOP_PADFRAME_CONFIG_PERMIT[18] & ~reg_be))) |
               (addr_hit[19] & (|(TOP_PADFRAME_CONFIG_PERMIT[19] & ~reg_be))) |
               (addr_hit[20] & (|(TOP_PADFRAME_CONFIG_PERMIT[20] & ~reg_be))) |
               (addr_hit[21] & (|(TOP_PADFRAME_CONFIG_PERMIT[21] & ~reg_be))) |
               (addr_hit[22] & (|(TOP_PADFRAME_CONFIG_PERMIT[22] & ~reg_be)))));
  end

  assign pad_fll_host_slew_en_we = addr_hit[1] & reg_we & !reg_error;
  assign pad_fll_host_slew_en_wd = reg_wdata[1];

  assign pad_fll_host_drv_str_we = addr_hit[1] & reg_we & !reg_error;
  assign pad_fll_host_drv_str_wd = reg_wdata[3:2];

  assign pad_fll_secd_slew_en_we = addr_hit[2] & reg_we & !reg_error;
  assign pad_fll_secd_slew_en_wd = reg_wdata[1];

  assign pad_fll_secd_drv_str_we = addr_hit[2] & reg_we & !reg_error;
  assign pad_fll_secd_drv_str_wd = reg_wdata[3:2];

  assign pad_jtag_tdo_slew_en_we = addr_hit[3] & reg_we & !reg_error;
  assign pad_jtag_tdo_slew_en_wd = reg_wdata[1];

  assign pad_jtag_tdo_drv_str_we = addr_hit[3] & reg_we & !reg_error;
  assign pad_jtag_tdo_drv_str_wd = reg_wdata[3:2];

  assign pad_uart_tx_slew_en_we = addr_hit[4] & reg_we & !reg_error;
  assign pad_uart_tx_slew_en_wd = reg_wdata[1];

  assign pad_uart_tx_drv_str_we = addr_hit[4] & reg_we & !reg_error;
  assign pad_uart_tx_drv_str_wd = reg_wdata[3:2];

  assign pad_gpio_0_pad_en_we = addr_hit[5] & reg_we & !reg_error;
  assign pad_gpio_0_pad_en_wd = reg_wdata[0];

  assign pad_gpio_0_slew_en_we = addr_hit[5] & reg_we & !reg_error;
  assign pad_gpio_0_slew_en_wd = reg_wdata[1];

  assign pad_gpio_0_drv_str_we = addr_hit[5] & reg_we & !reg_error;
  assign pad_gpio_0_drv_str_wd = reg_wdata[3:2];

  assign pad_gpio_0_pd_en_we = addr_hit[5] & reg_we & !reg_error;
  assign pad_gpio_0_pd_en_wd = reg_wdata[4];

  assign pad_gpio_0_pu_en_we = addr_hit[5] & reg_we & !reg_error;
  assign pad_gpio_0_pu_en_wd = reg_wdata[5];

  assign pad_gpio_0_smt_en_we = addr_hit[5] & reg_we & !reg_error;
  assign pad_gpio_0_smt_en_wd = reg_wdata[6];

  assign pad_gpio_1_pad_en_we = addr_hit[6] & reg_we & !reg_error;
  assign pad_gpio_1_pad_en_wd = reg_wdata[0];

  assign pad_gpio_1_slew_en_we = addr_hit[6] & reg_we & !reg_error;
  assign pad_gpio_1_slew_en_wd = reg_wdata[1];

  assign pad_gpio_1_drv_str_we = addr_hit[6] & reg_we & !reg_error;
  assign pad_gpio_1_drv_str_wd = reg_wdata[3:2];

  assign pad_gpio_1_pd_en_we = addr_hit[6] & reg_we & !reg_error;
  assign pad_gpio_1_pd_en_wd = reg_wdata[4];

  assign pad_gpio_1_pu_en_we = addr_hit[6] & reg_we & !reg_error;
  assign pad_gpio_1_pu_en_wd = reg_wdata[5];

  assign pad_gpio_1_smt_en_we = addr_hit[6] & reg_we & !reg_error;
  assign pad_gpio_1_smt_en_wd = reg_wdata[6];

  assign pad_gpio_2_pad_en_we = addr_hit[7] & reg_we & !reg_error;
  assign pad_gpio_2_pad_en_wd = reg_wdata[0];

  assign pad_gpio_2_slew_en_we = addr_hit[7] & reg_we & !reg_error;
  assign pad_gpio_2_slew_en_wd = reg_wdata[1];

  assign pad_gpio_2_drv_str_we = addr_hit[7] & reg_we & !reg_error;
  assign pad_gpio_2_drv_str_wd = reg_wdata[3:2];

  assign pad_gpio_2_pd_en_we = addr_hit[7] & reg_we & !reg_error;
  assign pad_gpio_2_pd_en_wd = reg_wdata[4];

  assign pad_gpio_2_pu_en_we = addr_hit[7] & reg_we & !reg_error;
  assign pad_gpio_2_pu_en_wd = reg_wdata[5];

  assign pad_gpio_2_smt_en_we = addr_hit[7] & reg_we & !reg_error;
  assign pad_gpio_2_smt_en_wd = reg_wdata[6];

  assign pad_gpio_3_pad_en_we = addr_hit[8] & reg_we & !reg_error;
  assign pad_gpio_3_pad_en_wd = reg_wdata[0];

  assign pad_gpio_3_slew_en_we = addr_hit[8] & reg_we & !reg_error;
  assign pad_gpio_3_slew_en_wd = reg_wdata[1];

  assign pad_gpio_3_drv_str_we = addr_hit[8] & reg_we & !reg_error;
  assign pad_gpio_3_drv_str_wd = reg_wdata[3:2];

  assign pad_gpio_3_pd_en_we = addr_hit[8] & reg_we & !reg_error;
  assign pad_gpio_3_pd_en_wd = reg_wdata[4];

  assign pad_gpio_3_pu_en_we = addr_hit[8] & reg_we & !reg_error;
  assign pad_gpio_3_pu_en_wd = reg_wdata[5];

  assign pad_gpio_3_smt_en_we = addr_hit[8] & reg_we & !reg_error;
  assign pad_gpio_3_smt_en_wd = reg_wdata[6];

  assign pad_jtag_ot_tdo_slew_en_we = addr_hit[9] & reg_we & !reg_error;
  assign pad_jtag_ot_tdo_slew_en_wd = reg_wdata[1];

  assign pad_jtag_ot_tdo_drv_str_we = addr_hit[9] & reg_we & !reg_error;
  assign pad_jtag_ot_tdo_drv_str_wd = reg_wdata[3:2];

  assign pad_ot_uart_tx_slew_en_we = addr_hit[10] & reg_we & !reg_error;
  assign pad_ot_uart_tx_slew_en_wd = reg_wdata[1];

  assign pad_ot_uart_tx_drv_str_we = addr_hit[10] & reg_we & !reg_error;
  assign pad_ot_uart_tx_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_sck_pad_en_we = addr_hit[11] & reg_we & !reg_error;
  assign pad_spih_sck_pad_en_wd = reg_wdata[0];

  assign pad_spih_sck_slew_en_we = addr_hit[11] & reg_we & !reg_error;
  assign pad_spih_sck_slew_en_wd = reg_wdata[1];

  assign pad_spih_sck_drv_str_we = addr_hit[11] & reg_we & !reg_error;
  assign pad_spih_sck_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_csb_pad_en_we = addr_hit[12] & reg_we & !reg_error;
  assign pad_spih_csb_pad_en_wd = reg_wdata[0];

  assign pad_spih_csb_slew_en_we = addr_hit[12] & reg_we & !reg_error;
  assign pad_spih_csb_slew_en_wd = reg_wdata[1];

  assign pad_spih_csb_drv_str_we = addr_hit[12] & reg_we & !reg_error;
  assign pad_spih_csb_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_sd_0_pad_en_we = addr_hit[13] & reg_we & !reg_error;
  assign pad_spih_sd_0_pad_en_wd = reg_wdata[0];

  assign pad_spih_sd_0_slew_en_we = addr_hit[13] & reg_we & !reg_error;
  assign pad_spih_sd_0_slew_en_wd = reg_wdata[1];

  assign pad_spih_sd_0_drv_str_we = addr_hit[13] & reg_we & !reg_error;
  assign pad_spih_sd_0_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_sd_0_pd_en_we = addr_hit[13] & reg_we & !reg_error;
  assign pad_spih_sd_0_pd_en_wd = reg_wdata[4];

  assign pad_spih_sd_0_pu_en_we = addr_hit[13] & reg_we & !reg_error;
  assign pad_spih_sd_0_pu_en_wd = reg_wdata[5];

  assign pad_spih_sd_0_smt_en_we = addr_hit[13] & reg_we & !reg_error;
  assign pad_spih_sd_0_smt_en_wd = reg_wdata[6];

  assign pad_spih_sd_1_pad_en_we = addr_hit[14] & reg_we & !reg_error;
  assign pad_spih_sd_1_pad_en_wd = reg_wdata[0];

  assign pad_spih_sd_1_slew_en_we = addr_hit[14] & reg_we & !reg_error;
  assign pad_spih_sd_1_slew_en_wd = reg_wdata[1];

  assign pad_spih_sd_1_drv_str_we = addr_hit[14] & reg_we & !reg_error;
  assign pad_spih_sd_1_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_sd_1_pd_en_we = addr_hit[14] & reg_we & !reg_error;
  assign pad_spih_sd_1_pd_en_wd = reg_wdata[4];

  assign pad_spih_sd_1_pu_en_we = addr_hit[14] & reg_we & !reg_error;
  assign pad_spih_sd_1_pu_en_wd = reg_wdata[5];

  assign pad_spih_sd_1_smt_en_we = addr_hit[14] & reg_we & !reg_error;
  assign pad_spih_sd_1_smt_en_wd = reg_wdata[6];

  assign pad_spih_sd_2_pad_en_we = addr_hit[15] & reg_we & !reg_error;
  assign pad_spih_sd_2_pad_en_wd = reg_wdata[0];

  assign pad_spih_sd_2_slew_en_we = addr_hit[15] & reg_we & !reg_error;
  assign pad_spih_sd_2_slew_en_wd = reg_wdata[1];

  assign pad_spih_sd_2_drv_str_we = addr_hit[15] & reg_we & !reg_error;
  assign pad_spih_sd_2_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_sd_2_pd_en_we = addr_hit[15] & reg_we & !reg_error;
  assign pad_spih_sd_2_pd_en_wd = reg_wdata[4];

  assign pad_spih_sd_2_pu_en_we = addr_hit[15] & reg_we & !reg_error;
  assign pad_spih_sd_2_pu_en_wd = reg_wdata[5];

  assign pad_spih_sd_2_smt_en_we = addr_hit[15] & reg_we & !reg_error;
  assign pad_spih_sd_2_smt_en_wd = reg_wdata[6];

  assign pad_spih_sd_3_pad_en_we = addr_hit[16] & reg_we & !reg_error;
  assign pad_spih_sd_3_pad_en_wd = reg_wdata[0];

  assign pad_spih_sd_3_slew_en_we = addr_hit[16] & reg_we & !reg_error;
  assign pad_spih_sd_3_slew_en_wd = reg_wdata[1];

  assign pad_spih_sd_3_drv_str_we = addr_hit[16] & reg_we & !reg_error;
  assign pad_spih_sd_3_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_sd_3_pd_en_we = addr_hit[16] & reg_we & !reg_error;
  assign pad_spih_sd_3_pd_en_wd = reg_wdata[4];

  assign pad_spih_sd_3_pu_en_we = addr_hit[16] & reg_we & !reg_error;
  assign pad_spih_sd_3_pu_en_wd = reg_wdata[5];

  assign pad_spih_sd_3_smt_en_we = addr_hit[16] & reg_we & !reg_error;
  assign pad_spih_sd_3_smt_en_wd = reg_wdata[6];

  assign pad_spih_ot_sck_pad_en_we = addr_hit[17] & reg_we & !reg_error;
  assign pad_spih_ot_sck_pad_en_wd = reg_wdata[0];

  assign pad_spih_ot_sck_slew_en_we = addr_hit[17] & reg_we & !reg_error;
  assign pad_spih_ot_sck_slew_en_wd = reg_wdata[1];

  assign pad_spih_ot_sck_drv_str_we = addr_hit[17] & reg_we & !reg_error;
  assign pad_spih_ot_sck_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_ot_csb_pad_en_we = addr_hit[18] & reg_we & !reg_error;
  assign pad_spih_ot_csb_pad_en_wd = reg_wdata[0];

  assign pad_spih_ot_csb_slew_en_we = addr_hit[18] & reg_we & !reg_error;
  assign pad_spih_ot_csb_slew_en_wd = reg_wdata[1];

  assign pad_spih_ot_csb_drv_str_we = addr_hit[18] & reg_we & !reg_error;
  assign pad_spih_ot_csb_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_ot_sd_0_pad_en_we = addr_hit[19] & reg_we & !reg_error;
  assign pad_spih_ot_sd_0_pad_en_wd = reg_wdata[0];

  assign pad_spih_ot_sd_0_slew_en_we = addr_hit[19] & reg_we & !reg_error;
  assign pad_spih_ot_sd_0_slew_en_wd = reg_wdata[1];

  assign pad_spih_ot_sd_0_drv_str_we = addr_hit[19] & reg_we & !reg_error;
  assign pad_spih_ot_sd_0_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_ot_sd_0_pd_en_we = addr_hit[19] & reg_we & !reg_error;
  assign pad_spih_ot_sd_0_pd_en_wd = reg_wdata[4];

  assign pad_spih_ot_sd_0_pu_en_we = addr_hit[19] & reg_we & !reg_error;
  assign pad_spih_ot_sd_0_pu_en_wd = reg_wdata[5];

  assign pad_spih_ot_sd_0_smt_en_we = addr_hit[19] & reg_we & !reg_error;
  assign pad_spih_ot_sd_0_smt_en_wd = reg_wdata[6];

  assign pad_spih_ot_sd_1_pad_en_we = addr_hit[20] & reg_we & !reg_error;
  assign pad_spih_ot_sd_1_pad_en_wd = reg_wdata[0];

  assign pad_spih_ot_sd_1_slew_en_we = addr_hit[20] & reg_we & !reg_error;
  assign pad_spih_ot_sd_1_slew_en_wd = reg_wdata[1];

  assign pad_spih_ot_sd_1_drv_str_we = addr_hit[20] & reg_we & !reg_error;
  assign pad_spih_ot_sd_1_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_ot_sd_1_pd_en_we = addr_hit[20] & reg_we & !reg_error;
  assign pad_spih_ot_sd_1_pd_en_wd = reg_wdata[4];

  assign pad_spih_ot_sd_1_pu_en_we = addr_hit[20] & reg_we & !reg_error;
  assign pad_spih_ot_sd_1_pu_en_wd = reg_wdata[5];

  assign pad_spih_ot_sd_1_smt_en_we = addr_hit[20] & reg_we & !reg_error;
  assign pad_spih_ot_sd_1_smt_en_wd = reg_wdata[6];

  assign pad_spih_ot_sd_2_pad_en_we = addr_hit[21] & reg_we & !reg_error;
  assign pad_spih_ot_sd_2_pad_en_wd = reg_wdata[0];

  assign pad_spih_ot_sd_2_slew_en_we = addr_hit[21] & reg_we & !reg_error;
  assign pad_spih_ot_sd_2_slew_en_wd = reg_wdata[1];

  assign pad_spih_ot_sd_2_drv_str_we = addr_hit[21] & reg_we & !reg_error;
  assign pad_spih_ot_sd_2_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_ot_sd_2_pd_en_we = addr_hit[21] & reg_we & !reg_error;
  assign pad_spih_ot_sd_2_pd_en_wd = reg_wdata[4];

  assign pad_spih_ot_sd_2_pu_en_we = addr_hit[21] & reg_we & !reg_error;
  assign pad_spih_ot_sd_2_pu_en_wd = reg_wdata[5];

  assign pad_spih_ot_sd_2_smt_en_we = addr_hit[21] & reg_we & !reg_error;
  assign pad_spih_ot_sd_2_smt_en_wd = reg_wdata[6];

  assign pad_spih_ot_sd_3_pad_en_we = addr_hit[22] & reg_we & !reg_error;
  assign pad_spih_ot_sd_3_pad_en_wd = reg_wdata[0];

  assign pad_spih_ot_sd_3_slew_en_we = addr_hit[22] & reg_we & !reg_error;
  assign pad_spih_ot_sd_3_slew_en_wd = reg_wdata[1];

  assign pad_spih_ot_sd_3_drv_str_we = addr_hit[22] & reg_we & !reg_error;
  assign pad_spih_ot_sd_3_drv_str_wd = reg_wdata[3:2];

  assign pad_spih_ot_sd_3_pd_en_we = addr_hit[22] & reg_we & !reg_error;
  assign pad_spih_ot_sd_3_pd_en_wd = reg_wdata[4];

  assign pad_spih_ot_sd_3_pu_en_we = addr_hit[22] & reg_we & !reg_error;
  assign pad_spih_ot_sd_3_pu_en_wd = reg_wdata[5];

  assign pad_spih_ot_sd_3_smt_en_we = addr_hit[22] & reg_we & !reg_error;
  assign pad_spih_ot_sd_3_smt_en_wd = reg_wdata[6];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[15:0] = info_hw_version_qs;
        reg_rdata_next[31:16] = info_pad_count_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[1] = pad_fll_host_slew_en_qs;
        reg_rdata_next[3:2] = pad_fll_host_drv_str_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[1] = pad_fll_secd_slew_en_qs;
        reg_rdata_next[3:2] = pad_fll_secd_drv_str_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[1] = pad_jtag_tdo_slew_en_qs;
        reg_rdata_next[3:2] = pad_jtag_tdo_drv_str_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[1] = pad_uart_tx_slew_en_qs;
        reg_rdata_next[3:2] = pad_uart_tx_drv_str_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = pad_gpio_0_pad_en_qs;
        reg_rdata_next[1] = pad_gpio_0_slew_en_qs;
        reg_rdata_next[3:2] = pad_gpio_0_drv_str_qs;
        reg_rdata_next[4] = pad_gpio_0_pd_en_qs;
        reg_rdata_next[5] = pad_gpio_0_pu_en_qs;
        reg_rdata_next[6] = pad_gpio_0_smt_en_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[0] = pad_gpio_1_pad_en_qs;
        reg_rdata_next[1] = pad_gpio_1_slew_en_qs;
        reg_rdata_next[3:2] = pad_gpio_1_drv_str_qs;
        reg_rdata_next[4] = pad_gpio_1_pd_en_qs;
        reg_rdata_next[5] = pad_gpio_1_pu_en_qs;
        reg_rdata_next[6] = pad_gpio_1_smt_en_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[0] = pad_gpio_2_pad_en_qs;
        reg_rdata_next[1] = pad_gpio_2_slew_en_qs;
        reg_rdata_next[3:2] = pad_gpio_2_drv_str_qs;
        reg_rdata_next[4] = pad_gpio_2_pd_en_qs;
        reg_rdata_next[5] = pad_gpio_2_pu_en_qs;
        reg_rdata_next[6] = pad_gpio_2_smt_en_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[0] = pad_gpio_3_pad_en_qs;
        reg_rdata_next[1] = pad_gpio_3_slew_en_qs;
        reg_rdata_next[3:2] = pad_gpio_3_drv_str_qs;
        reg_rdata_next[4] = pad_gpio_3_pd_en_qs;
        reg_rdata_next[5] = pad_gpio_3_pu_en_qs;
        reg_rdata_next[6] = pad_gpio_3_smt_en_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[1] = pad_jtag_ot_tdo_slew_en_qs;
        reg_rdata_next[3:2] = pad_jtag_ot_tdo_drv_str_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[1] = pad_ot_uart_tx_slew_en_qs;
        reg_rdata_next[3:2] = pad_ot_uart_tx_drv_str_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[0] = pad_spih_sck_pad_en_qs;
        reg_rdata_next[1] = pad_spih_sck_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_sck_drv_str_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[0] = pad_spih_csb_pad_en_qs;
        reg_rdata_next[1] = pad_spih_csb_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_csb_drv_str_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[0] = pad_spih_sd_0_pad_en_qs;
        reg_rdata_next[1] = pad_spih_sd_0_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_sd_0_drv_str_qs;
        reg_rdata_next[4] = pad_spih_sd_0_pd_en_qs;
        reg_rdata_next[5] = pad_spih_sd_0_pu_en_qs;
        reg_rdata_next[6] = pad_spih_sd_0_smt_en_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[0] = pad_spih_sd_1_pad_en_qs;
        reg_rdata_next[1] = pad_spih_sd_1_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_sd_1_drv_str_qs;
        reg_rdata_next[4] = pad_spih_sd_1_pd_en_qs;
        reg_rdata_next[5] = pad_spih_sd_1_pu_en_qs;
        reg_rdata_next[6] = pad_spih_sd_1_smt_en_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[0] = pad_spih_sd_2_pad_en_qs;
        reg_rdata_next[1] = pad_spih_sd_2_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_sd_2_drv_str_qs;
        reg_rdata_next[4] = pad_spih_sd_2_pd_en_qs;
        reg_rdata_next[5] = pad_spih_sd_2_pu_en_qs;
        reg_rdata_next[6] = pad_spih_sd_2_smt_en_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[0] = pad_spih_sd_3_pad_en_qs;
        reg_rdata_next[1] = pad_spih_sd_3_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_sd_3_drv_str_qs;
        reg_rdata_next[4] = pad_spih_sd_3_pd_en_qs;
        reg_rdata_next[5] = pad_spih_sd_3_pu_en_qs;
        reg_rdata_next[6] = pad_spih_sd_3_smt_en_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[0] = pad_spih_ot_sck_pad_en_qs;
        reg_rdata_next[1] = pad_spih_ot_sck_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_ot_sck_drv_str_qs;
      end

      addr_hit[18]: begin
        reg_rdata_next[0] = pad_spih_ot_csb_pad_en_qs;
        reg_rdata_next[1] = pad_spih_ot_csb_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_ot_csb_drv_str_qs;
      end

      addr_hit[19]: begin
        reg_rdata_next[0] = pad_spih_ot_sd_0_pad_en_qs;
        reg_rdata_next[1] = pad_spih_ot_sd_0_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_ot_sd_0_drv_str_qs;
        reg_rdata_next[4] = pad_spih_ot_sd_0_pd_en_qs;
        reg_rdata_next[5] = pad_spih_ot_sd_0_pu_en_qs;
        reg_rdata_next[6] = pad_spih_ot_sd_0_smt_en_qs;
      end

      addr_hit[20]: begin
        reg_rdata_next[0] = pad_spih_ot_sd_1_pad_en_qs;
        reg_rdata_next[1] = pad_spih_ot_sd_1_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_ot_sd_1_drv_str_qs;
        reg_rdata_next[4] = pad_spih_ot_sd_1_pd_en_qs;
        reg_rdata_next[5] = pad_spih_ot_sd_1_pu_en_qs;
        reg_rdata_next[6] = pad_spih_ot_sd_1_smt_en_qs;
      end

      addr_hit[21]: begin
        reg_rdata_next[0] = pad_spih_ot_sd_2_pad_en_qs;
        reg_rdata_next[1] = pad_spih_ot_sd_2_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_ot_sd_2_drv_str_qs;
        reg_rdata_next[4] = pad_spih_ot_sd_2_pd_en_qs;
        reg_rdata_next[5] = pad_spih_ot_sd_2_pu_en_qs;
        reg_rdata_next[6] = pad_spih_ot_sd_2_smt_en_qs;
      end

      addr_hit[22]: begin
        reg_rdata_next[0] = pad_spih_ot_sd_3_pad_en_qs;
        reg_rdata_next[1] = pad_spih_ot_sd_3_slew_en_qs;
        reg_rdata_next[3:2] = pad_spih_ot_sd_3_drv_str_qs;
        reg_rdata_next[4] = pad_spih_ot_sd_3_pd_en_qs;
        reg_rdata_next[5] = pad_spih_ot_sd_3_pu_en_qs;
        reg_rdata_next[6] = pad_spih_ot_sd_3_smt_en_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module top_padframe_config_reg_top_intf
#(
  parameter int AW = 7,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output top_padframe_config_reg_pkg::top_padframe_config_reg2hw_t reg2hw, // Write
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  top_padframe_config_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .devmode_i
  );
  
endmodule


