// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module top_padframe_config_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 4
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output top_padframe_config_reg_pkg::top_padframe_config_reg2hw_t reg2hw, // Write


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import top_padframe_config_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [15:0] info_hw_version_qs;
  logic [15:0] info_padgroup_count_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_1_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_1_wd;
  logic drv_str_cfg_drv_str_pg_1_we;
  logic [1:0] drv_str_cfg_drv_str_pg_2_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_2_wd;
  logic drv_str_cfg_drv_str_pg_2_we;
  logic [1:0] drv_str_cfg_drv_str_pg_3_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_3_wd;
  logic drv_str_cfg_drv_str_pg_3_we;
  logic [1:0] drv_str_cfg_drv_str_pg_4_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_4_wd;
  logic drv_str_cfg_drv_str_pg_4_we;
  logic [1:0] drv_str_cfg_drv_str_pg_5_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_5_wd;
  logic drv_str_cfg_drv_str_pg_5_we;
  logic [1:0] drv_str_cfg_drv_str_pg_6_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_6_wd;
  logic drv_str_cfg_drv_str_pg_6_we;
  logic [1:0] drv_str_cfg_drv_str_pg_7_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_7_wd;
  logic drv_str_cfg_drv_str_pg_7_we;
  logic [1:0] drv_str_cfg_drv_str_pg_8_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_8_wd;
  logic drv_str_cfg_drv_str_pg_8_we;
  logic [1:0] drv_str_cfg_drv_str_pg_9_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_9_wd;
  logic drv_str_cfg_drv_str_pg_9_we;
  logic [1:0] drv_str_cfg_drv_str_pg_10_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_10_wd;
  logic drv_str_cfg_drv_str_pg_10_we;
  logic [1:0] drv_str_cfg_drv_str_pg_11_qs;
  logic [1:0] drv_str_cfg_drv_str_pg_11_wd;
  logic drv_str_cfg_drv_str_pg_11_we;
  logic slw_cfg_slw_pg_1_qs;
  logic slw_cfg_slw_pg_1_wd;
  logic slw_cfg_slw_pg_1_we;
  logic slw_cfg_slw_pg_2_qs;
  logic slw_cfg_slw_pg_2_wd;
  logic slw_cfg_slw_pg_2_we;
  logic slw_cfg_slw_pg_3_qs;
  logic slw_cfg_slw_pg_3_wd;
  logic slw_cfg_slw_pg_3_we;
  logic slw_cfg_slw_pg_4_qs;
  logic slw_cfg_slw_pg_4_wd;
  logic slw_cfg_slw_pg_4_we;
  logic slw_cfg_slw_pg_5_qs;
  logic slw_cfg_slw_pg_5_wd;
  logic slw_cfg_slw_pg_5_we;
  logic slw_cfg_slw_pg_6_qs;
  logic slw_cfg_slw_pg_6_wd;
  logic slw_cfg_slw_pg_6_we;
  logic slw_cfg_slw_pg_7_qs;
  logic slw_cfg_slw_pg_7_wd;
  logic slw_cfg_slw_pg_7_we;
  logic slw_cfg_slw_pg_8_qs;
  logic slw_cfg_slw_pg_8_wd;
  logic slw_cfg_slw_pg_8_we;
  logic slw_cfg_slw_pg_9_qs;
  logic slw_cfg_slw_pg_9_wd;
  logic slw_cfg_slw_pg_9_we;
  logic slw_cfg_slw_pg_10_qs;
  logic slw_cfg_slw_pg_10_wd;
  logic slw_cfg_slw_pg_10_we;
  logic slw_cfg_slw_pg_11_qs;
  logic slw_cfg_slw_pg_11_wd;
  logic slw_cfg_slw_pg_11_we;

  // Register instances
  // R[info]: V(False)

  //   F[hw_version]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h2)
  ) u_info_hw_version (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.info.hw_version.q ),

    // to register interface (read)
    .qs     (info_hw_version_qs)
  );


  //   F[padgroup_count]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'hb)
  ) u_info_padgroup_count (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.info.padgroup_count.q ),

    // to register interface (read)
    .qs     (info_padgroup_count_qs)
  );


  // R[drv_str_cfg]: V(False)

  //   F[drv_str_pg_1]: 1:0
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_1_we),
    .wd     (drv_str_cfg_drv_str_pg_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_1.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_1_qs)
  );


  //   F[drv_str_pg_2]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_2_we),
    .wd     (drv_str_cfg_drv_str_pg_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_2.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_2_qs)
  );


  //   F[drv_str_pg_3]: 5:4
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_3_we),
    .wd     (drv_str_cfg_drv_str_pg_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_3.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_3_qs)
  );


  //   F[drv_str_pg_4]: 7:6
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_4 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_4_we),
    .wd     (drv_str_cfg_drv_str_pg_4_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_4.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_4_qs)
  );


  //   F[drv_str_pg_5]: 9:8
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_5 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_5_we),
    .wd     (drv_str_cfg_drv_str_pg_5_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_5.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_5_qs)
  );


  //   F[drv_str_pg_6]: 11:10
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_6 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_6_we),
    .wd     (drv_str_cfg_drv_str_pg_6_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_6.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_6_qs)
  );


  //   F[drv_str_pg_7]: 13:12
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_7 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_7_we),
    .wd     (drv_str_cfg_drv_str_pg_7_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_7.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_7_qs)
  );


  //   F[drv_str_pg_8]: 15:14
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_8 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_8_we),
    .wd     (drv_str_cfg_drv_str_pg_8_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_8.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_8_qs)
  );


  //   F[drv_str_pg_9]: 17:16
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_9 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_9_we),
    .wd     (drv_str_cfg_drv_str_pg_9_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_9.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_9_qs)
  );


  //   F[drv_str_pg_10]: 19:18
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_10 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_10_we),
    .wd     (drv_str_cfg_drv_str_pg_10_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_10.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_10_qs)
  );


  //   F[drv_str_pg_11]: 21:20
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_drv_str_cfg_drv_str_pg_11 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (drv_str_cfg_drv_str_pg_11_we),
    .wd     (drv_str_cfg_drv_str_pg_11_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.drv_str_cfg.drv_str_pg_11.q ),

    // to register interface (read)
    .qs     (drv_str_cfg_drv_str_pg_11_qs)
  );


  // R[slw_cfg]: V(False)

  //   F[slw_pg_1]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_1_we),
    .wd     (slw_cfg_slw_pg_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_1.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_1_qs)
  );


  //   F[slw_pg_2]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_2_we),
    .wd     (slw_cfg_slw_pg_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_2.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_2_qs)
  );


  //   F[slw_pg_3]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_3_we),
    .wd     (slw_cfg_slw_pg_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_3.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_3_qs)
  );


  //   F[slw_pg_4]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_4 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_4_we),
    .wd     (slw_cfg_slw_pg_4_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_4.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_4_qs)
  );


  //   F[slw_pg_5]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_5 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_5_we),
    .wd     (slw_cfg_slw_pg_5_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_5.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_5_qs)
  );


  //   F[slw_pg_6]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_6 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_6_we),
    .wd     (slw_cfg_slw_pg_6_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_6.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_6_qs)
  );


  //   F[slw_pg_7]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_7 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_7_we),
    .wd     (slw_cfg_slw_pg_7_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_7.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_7_qs)
  );


  //   F[slw_pg_8]: 7:7
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_8 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_8_we),
    .wd     (slw_cfg_slw_pg_8_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_8.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_8_qs)
  );


  //   F[slw_pg_9]: 8:8
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_9 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_9_we),
    .wd     (slw_cfg_slw_pg_9_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_9.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_9_qs)
  );


  //   F[slw_pg_10]: 9:9
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_10 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_10_we),
    .wd     (slw_cfg_slw_pg_10_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_10.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_10_qs)
  );


  //   F[slw_pg_11]: 10:10
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_slw_cfg_slw_pg_11 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (slw_cfg_slw_pg_11_we),
    .wd     (slw_cfg_slw_pg_11_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.slw_cfg.slw_pg_11.q ),

    // to register interface (read)
    .qs     (slw_cfg_slw_pg_11_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == TOP_PADFRAME_CONFIG_INFO_OFFSET);
    addr_hit[1] = (reg_addr == TOP_PADFRAME_CONFIG_DRV_STR_CFG_OFFSET);
    addr_hit[2] = (reg_addr == TOP_PADFRAME_CONFIG_SLW_CFG_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(TOP_PADFRAME_CONFIG_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(TOP_PADFRAME_CONFIG_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(TOP_PADFRAME_CONFIG_PERMIT[2] & ~reg_be)))));
  end

  assign drv_str_cfg_drv_str_pg_1_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_1_wd = reg_wdata[1:0];

  assign drv_str_cfg_drv_str_pg_2_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_2_wd = reg_wdata[3:2];

  assign drv_str_cfg_drv_str_pg_3_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_3_wd = reg_wdata[5:4];

  assign drv_str_cfg_drv_str_pg_4_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_4_wd = reg_wdata[7:6];

  assign drv_str_cfg_drv_str_pg_5_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_5_wd = reg_wdata[9:8];

  assign drv_str_cfg_drv_str_pg_6_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_6_wd = reg_wdata[11:10];

  assign drv_str_cfg_drv_str_pg_7_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_7_wd = reg_wdata[13:12];

  assign drv_str_cfg_drv_str_pg_8_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_8_wd = reg_wdata[15:14];

  assign drv_str_cfg_drv_str_pg_9_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_9_wd = reg_wdata[17:16];

  assign drv_str_cfg_drv_str_pg_10_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_10_wd = reg_wdata[19:18];

  assign drv_str_cfg_drv_str_pg_11_we = addr_hit[1] & reg_we & !reg_error;
  assign drv_str_cfg_drv_str_pg_11_wd = reg_wdata[21:20];

  assign slw_cfg_slw_pg_1_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_1_wd = reg_wdata[0];

  assign slw_cfg_slw_pg_2_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_2_wd = reg_wdata[1];

  assign slw_cfg_slw_pg_3_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_3_wd = reg_wdata[2];

  assign slw_cfg_slw_pg_4_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_4_wd = reg_wdata[3];

  assign slw_cfg_slw_pg_5_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_5_wd = reg_wdata[4];

  assign slw_cfg_slw_pg_6_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_6_wd = reg_wdata[5];

  assign slw_cfg_slw_pg_7_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_7_wd = reg_wdata[6];

  assign slw_cfg_slw_pg_8_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_8_wd = reg_wdata[7];

  assign slw_cfg_slw_pg_9_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_9_wd = reg_wdata[8];

  assign slw_cfg_slw_pg_10_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_10_wd = reg_wdata[9];

  assign slw_cfg_slw_pg_11_we = addr_hit[2] & reg_we & !reg_error;
  assign slw_cfg_slw_pg_11_wd = reg_wdata[10];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[15:0] = info_hw_version_qs;
        reg_rdata_next[31:16] = info_padgroup_count_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[1:0] = drv_str_cfg_drv_str_pg_1_qs;
        reg_rdata_next[3:2] = drv_str_cfg_drv_str_pg_2_qs;
        reg_rdata_next[5:4] = drv_str_cfg_drv_str_pg_3_qs;
        reg_rdata_next[7:6] = drv_str_cfg_drv_str_pg_4_qs;
        reg_rdata_next[9:8] = drv_str_cfg_drv_str_pg_5_qs;
        reg_rdata_next[11:10] = drv_str_cfg_drv_str_pg_6_qs;
        reg_rdata_next[13:12] = drv_str_cfg_drv_str_pg_7_qs;
        reg_rdata_next[15:14] = drv_str_cfg_drv_str_pg_8_qs;
        reg_rdata_next[17:16] = drv_str_cfg_drv_str_pg_9_qs;
        reg_rdata_next[19:18] = drv_str_cfg_drv_str_pg_10_qs;
        reg_rdata_next[21:20] = drv_str_cfg_drv_str_pg_11_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = slw_cfg_slw_pg_1_qs;
        reg_rdata_next[1] = slw_cfg_slw_pg_2_qs;
        reg_rdata_next[2] = slw_cfg_slw_pg_3_qs;
        reg_rdata_next[3] = slw_cfg_slw_pg_4_qs;
        reg_rdata_next[4] = slw_cfg_slw_pg_5_qs;
        reg_rdata_next[5] = slw_cfg_slw_pg_6_qs;
        reg_rdata_next[6] = slw_cfg_slw_pg_7_qs;
        reg_rdata_next[7] = slw_cfg_slw_pg_8_qs;
        reg_rdata_next[8] = slw_cfg_slw_pg_9_qs;
        reg_rdata_next[9] = slw_cfg_slw_pg_10_qs;
        reg_rdata_next[10] = slw_cfg_slw_pg_11_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module top_padframe_config_reg_top_intf
#(
  parameter int AW = 4,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output top_padframe_config_reg_pkg::top_padframe_config_reg2hw_t reg2hw, // Write
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  top_padframe_config_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .devmode_i
  );
  
endmodule


