// Generated register defines for top_padframe_config

// Copyright information found in source file:
// Copyright 2026 Fondazione Chips-IT.

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef _TOP_PADFRAME_CONFIG_REG_DEFS_
#define _TOP_PADFRAME_CONFIG_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define TOP_PADFRAME_CONFIG_PARAM_REG_WIDTH 32

// Read-only IP Information register
#define TOP_PADFRAME_CONFIG_INFO_REG_OFFSET 0x0
#define TOP_PADFRAME_CONFIG_INFO_HW_VERSION_MASK 0xffff
#define TOP_PADFRAME_CONFIG_INFO_HW_VERSION_OFFSET 0
#define TOP_PADFRAME_CONFIG_INFO_HW_VERSION_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_INFO_HW_VERSION_MASK, .index = TOP_PADFRAME_CONFIG_INFO_HW_VERSION_OFFSET })
#define TOP_PADFRAME_CONFIG_INFO_PAD_COUNT_MASK 0xffff
#define TOP_PADFRAME_CONFIG_INFO_PAD_COUNT_OFFSET 16
#define TOP_PADFRAME_CONFIG_INFO_PAD_COUNT_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_INFO_PAD_COUNT_MASK, .index = TOP_PADFRAME_CONFIG_INFO_PAD_COUNT_OFFSET })

// Configuration register for PAD_FLL_HOST
#define TOP_PADFRAME_CONFIG_PAD_FLL_HOST_REG_OFFSET 0x4
#define TOP_PADFRAME_CONFIG_PAD_FLL_HOST_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_FLL_HOST_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_FLL_HOST_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_FLL_HOST_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_FLL_HOST_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_FLL_HOST_DRV_STR_OFFSET })

// Configuration register for PAD_FLL_SECD
#define TOP_PADFRAME_CONFIG_PAD_FLL_SECD_REG_OFFSET 0x8
#define TOP_PADFRAME_CONFIG_PAD_FLL_SECD_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_FLL_SECD_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_FLL_SECD_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_FLL_SECD_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_FLL_SECD_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_FLL_SECD_DRV_STR_OFFSET })

// Configuration register for PAD_JTAG_TDO
#define TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_REG_OFFSET 0xc
#define TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_JTAG_TDO_DRV_STR_OFFSET })

// Configuration register for PAD_UART_TX
#define TOP_PADFRAME_CONFIG_PAD_UART_TX_REG_OFFSET 0x10
#define TOP_PADFRAME_CONFIG_PAD_UART_TX_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_UART_TX_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_UART_TX_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_UART_TX_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_UART_TX_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_UART_TX_DRV_STR_OFFSET })

// Configuration register for PAD_GPIO_0
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_REG_OFFSET 0x14
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_GPIO_0_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_GPIO_0_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_GPIO_0_SMT_EN_BIT 6

// Configuration register for PAD_GPIO_1
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_REG_OFFSET 0x18
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_GPIO_1_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_GPIO_1_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_GPIO_1_SMT_EN_BIT 6

// Configuration register for PAD_GPIO_2
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_REG_OFFSET 0x1c
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_GPIO_2_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_GPIO_2_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_GPIO_2_SMT_EN_BIT 6

// Configuration register for PAD_GPIO_3
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_REG_OFFSET 0x20
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_GPIO_3_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_GPIO_3_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_GPIO_3_SMT_EN_BIT 6

// Configuration register for PAD_JTAG_OT_TDO
#define TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_REG_OFFSET 0x24
#define TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_JTAG_OT_TDO_DRV_STR_OFFSET })

// Configuration register for PAD_OT_UART_TX
#define TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_REG_OFFSET 0x28
#define TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_OT_UART_TX_DRV_STR_OFFSET })

// Configuration register for PAD_SPIH_SCK
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_REG_OFFSET 0x2c
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_SCK_DRV_STR_OFFSET })

// Configuration register for PAD_SPIH_CSB
#define TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_REG_OFFSET 0x30
#define TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_CSB_DRV_STR_OFFSET })

// Configuration register for PAD_SPIH_SD_0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_REG_OFFSET 0x34
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_0_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_SD_1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_REG_OFFSET 0x38
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_1_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_SD_2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_REG_OFFSET 0x3c
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_2_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_SD_3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_REG_OFFSET 0x40
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_SD_3_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_OT_SCK
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_REG_OFFSET 0x44
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SCK_DRV_STR_OFFSET })

// Configuration register for PAD_SPIH_OT_CSB
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_REG_OFFSET 0x48
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_CSB_DRV_STR_OFFSET })

// Configuration register for PAD_SPIH_OT_SD_0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_REG_OFFSET 0x4c
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_0_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_OT_SD_1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_REG_OFFSET 0x50
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_1_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_OT_SD_2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_REG_OFFSET 0x54
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_2_SMT_EN_BIT 6

// Configuration register for PAD_SPIH_OT_SD_3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_REG_OFFSET 0x58
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_PAD_EN_BIT 0
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_SLEW_EN_BIT 1
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_DRV_STR_MASK 0x3
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_DRV_STR_OFFSET 2
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_DRV_STR_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_DRV_STR_MASK, .index = TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_DRV_STR_OFFSET })
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_PD_EN_BIT 4
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_PU_EN_BIT 5
#define TOP_PADFRAME_CONFIG_PAD_SPIH_OT_SD_3_SMT_EN_BIT 6

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _TOP_PADFRAME_CONFIG_REG_DEFS_
// End generated register defines for top_padframe_config