// Generated register defines for top_padframe_config

// Copyright information found in source file:
// Copyright 2026 Fondazione Chips-IT.

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef _TOP_PADFRAME_CONFIG_REG_DEFS_
#define _TOP_PADFRAME_CONFIG_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define TOP_PADFRAME_CONFIG_PARAM_REG_WIDTH 32

// Read-only IP Information register
#define TOP_PADFRAME_CONFIG_INFO_REG_OFFSET 0x0
#define TOP_PADFRAME_CONFIG_INFO_HW_VERSION_MASK 0xffff
#define TOP_PADFRAME_CONFIG_INFO_HW_VERSION_OFFSET 0
#define TOP_PADFRAME_CONFIG_INFO_HW_VERSION_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_INFO_HW_VERSION_MASK, .index = TOP_PADFRAME_CONFIG_INFO_HW_VERSION_OFFSET })
#define TOP_PADFRAME_CONFIG_INFO_PADGROUP_COUNT_MASK 0xffff
#define TOP_PADFRAME_CONFIG_INFO_PADGROUP_COUNT_OFFSET 16
#define TOP_PADFRAME_CONFIG_INFO_PADGROUP_COUNT_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_INFO_PADGROUP_COUNT_MASK, .index = TOP_PADFRAME_CONFIG_INFO_PADGROUP_COUNT_OFFSET })

// Pad groups drive strength configuration register
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_REG_OFFSET 0x4
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_1_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_1_OFFSET 0
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_1_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_1_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_1_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_2_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_2_OFFSET 2
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_2_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_2_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_2_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_3_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_3_OFFSET 4
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_3_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_3_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_3_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_4_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_4_OFFSET 6
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_4_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_4_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_4_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_5_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_5_OFFSET 8
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_5_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_5_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_5_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_6_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_6_OFFSET 10
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_6_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_6_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_6_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_7_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_7_OFFSET 12
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_7_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_7_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_7_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_8_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_8_OFFSET 14
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_8_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_8_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_8_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_9_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_9_OFFSET 16
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_9_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_9_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_9_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_10_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_10_OFFSET 18
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_10_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_10_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_10_OFFSET })
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_11_MASK 0x3
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_11_OFFSET 20
#define TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_11_FIELD \
  ((bitfield_field32_t) { .mask = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_11_MASK, .index = TOP_PADFRAME_CONFIG_DRV_STR_CFG_DRV_STR_PG_11_OFFSET })

// Pad groups slew enable configuration register. 0 for VDDIO=1.8V, 1 for
// VDDIO=1.6V or 1.2V
#define TOP_PADFRAME_CONFIG_SLW_CFG_REG_OFFSET 0x8
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_1_BIT 0
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_2_BIT 1
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_3_BIT 2
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_4_BIT 3
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_5_BIT 4
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_6_BIT 5
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_7_BIT 6
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_8_BIT 7
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_9_BIT 8
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_10_BIT 9
#define TOP_PADFRAME_CONFIG_SLW_CFG_SLW_PG_11_BIT 10

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _TOP_PADFRAME_CONFIG_REG_DEFS_
// End generated register defines for top_padframe_config