# Copyright 2026 Fondazione Chips-IT.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Generated IO file iofile/scarv.io from iofile/astral_padframe.csv and iofile/scarv_config.yml.
# This file is automatically generated.

( globals
	version = 3
	io_order = counterclockwise
)

( row_margin
	( bottom
		( io_row ring_number = 1 margin = 0.0 )
	)
	( right
		( io_row ring_number = 1 margin = 0.0 )
	)
	( top
		( io_row ring_number = 1 margin = 0.0 )
	)
	( left
		( io_row ring_number = 1 margin = 0.0 )
	)
)

( iopad
	( bottomleft
		( locals ring_number = 1 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_corner_0/i_gf22_in_tc_pad_corner" orientation = R0 )
	)
	( bottomright
		( locals ring_number = 1 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_corner_1/i_gf22_in_tc_pad_corner" orientation = MY )
	)
	( topright
		( locals ring_number = 1 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_corner_2/i_gf22_in_tc_pad_corner" orientation = R180 )
	)
	( topleft
		( locals ring_number = 1 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_corner_3/i_gf22_in_tc_pad_corner" orientation = MX )
	)
	( bottom
		( locals ring_number = 1 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_core_0_v/genblk1_i_gf22_in_tc_pad_vdd_core_v" orientation = R0 offset = 178.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_ot_boot_mode/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 273.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_ot_tclk/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 364.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_ot_trst_n/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 456.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_io_0_v/genblk1_i_gf22_in_tc_pad_vdd_io_v" orientation = R0 offset = 547.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_ot_tms/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 640.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_ot_tdi/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 731.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_ot_tdo/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 823.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_ot_uart_tx/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 915.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_ot_uart_rx/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 1007.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_sck/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 1098.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_io_0_v/genblk1_i_gf22_in_tc_pad_vss_io_v" orientation = R0 offset = 1189.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_core_0_v/genblk1_i_gf22_in_tc_pad_vss_core_v" orientation = R0 offset = 1282.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_core_1_v/genblk1_i_gf22_in_tc_pad_vdd_core_v" orientation = R0 offset = 1371.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_pwr_mng_south/genblk1_genblk1_i_gf22_in_tc_pad_pwr_mng_v" orientation = R0 offset = 1472.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_csb/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 1557.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_sd_0/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 1649.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_sd_1/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 1741.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_io_1_v/genblk1_i_gf22_in_tc_pad_vdd_io_v" orientation = R0 offset = 1832.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_sd_2/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 1924.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_sd_3/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2016.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_ot_sck/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2108.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_ot_csb/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2200.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_ot_sd_0/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2291.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_io_1_v/genblk1_i_gf22_in_tc_pad_vss_io_v" orientation = R0 offset = 2382.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_ot_sd_1/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2475.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_ot_sd_2/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2567.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_spih_ot_sd_3/genblk1_i_gf22_in_tc_pad_bidir_v" orientation = R0 offset = 2658.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_core_1_v/genblk1_i_gf22_in_tc_pad_vss_core_v" orientation = R0 offset = 2750.0 )
	)
	( left
		( locals ring_number = 1 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_core_0_h/genblk1_i_gf22_in_tc_pad_vdd_core_h" orientation = R0 offset = 178.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_fll_host/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 273.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_fll_secd/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 364.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_fll_bypass/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 456.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_io_0_h/genblk1_i_gf22_in_tc_pad_vdd_io_h" orientation = R0 offset = 547.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_pwr_on_rst_n/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 640.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_boot_mode_0/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 731.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_boot_mode_1/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 823.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_secure_boot/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 915.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_ref_clk/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 1007.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_core_1_h/genblk1_i_gf22_in_tc_pad_vdd_core_h" orientation = R0 offset = 1095.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_io_0_h/genblk1_i_gf22_in_tc_pad_vss_io_h" orientation = R0 offset = 1189.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_core_0_h/genblk1_i_gf22_in_tc_pad_vss_core_h" orientation = R0 offset = 1282.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_core_2_h/genblk1_i_gf22_in_tc_pad_vdd_core_h" orientation = R0 offset = 1371.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_pwr_mng_west/genblk1_genblk1_i_gf22_in_tc_pad_pwr_mng_h" orientation = R0 offset = 1472.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_tclk/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 1557.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_trst_n/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 1649.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_tms/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 1741.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vdd_io_1_h/genblk1_i_gf22_in_tc_pad_vdd_io_h" orientation = R0 offset = 1832.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_tdi/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 1924.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_jtag_tdo/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2016.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_uart_tx/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2108.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_uart_rx/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2200.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_gpio_0/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2291.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_io_1_h/genblk1_i_gf22_in_tc_pad_vss_io_h" orientation = R0 offset = 2382.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_gpio_1/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2475.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_gpio_2/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2567.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_gpio_3/genblk1_i_gf22_in_tc_pad_bidir_h" orientation = R0 offset = 2658.0 )
		( inst name = "i_top_padframe_wrapper/i_astral_padframe/i_botl/i_botl_pads/i_vss_core_1_h/genblk1_i_gf22_in_tc_pad_vss_core_h" orientation = R0 offset = 2750.0 )
	)
)
