
// File auto-generated by Padrick unknown
// 
// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Assignment Macros
// Assigns all members of port struct to another struct with same names but potentially different order


